spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      This tells what should hibernate do when the project starts. do this only when you are
#      in developement mode, remove it when the development is done
      ddl-auto: update
#      show-sql: true will  allow us to see the queries in the log
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect